algoritmo "exercicio6"
// Função :
// Autor :
// Data : 20/04/2017
// Seção de Declarações 
var
   ingressos:inteiro
   preco,lucro:real
inicio
// Seção de Comandos
   ingressos <- 120
   preco <- 5.0
   enquanto (preco >= 1.0) faca
       lucro <- preco*ingressos - 200
       escreval ("Com o ingresso a: ",preco," R$ o lucro máximo é: ",lucro," com ",ingressos," vendidos")
       preco <- preco - 0.5
       ingressos <- ingressos + 26
   fimenquanto
   
fimalgoritmo
