algoritmo "Notas e pesos"
// Função :
// Autor :
// Data : 13/03/2017
// Seção de Declarações 
var
   n1,n2,n3,p1,p2,p3,media:Real
inicio
// Seção de Comandos 
   Escreval ("Digite a primeira, segunda e terceira nota:")
   leia (n1,n2,n3)
   Escreval ("Digite os pesos respectivamente:")
   leia (p1,p2,p3)
   media <- (n1*p1*0.1)+(n2*p2*0.1)+(n3*p3*0.1)
   escreval ("Sua média é :",media)
   
fimalgoritmo
